# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scout-gear 1.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "scout-gear".freeze
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Miguel Vazquez".freeze]
  s.date = "2023-03-24"
  s.description = "Temporary files, logs, etc.".freeze
  s.email = "mikisvaz@gmail.com".freeze
  s.executables = ["scout".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".vimproject",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/scout",
    "lib/scout-gear.rb",
    "lib/scout/exceptions.rb",
    "lib/scout/indiferent_hash.rb",
    "lib/scout/indiferent_hash/case_insensitive.rb",
    "lib/scout/indiferent_hash/options.rb",
    "lib/scout/log.rb",
    "lib/scout/log/color.rb",
    "lib/scout/log/color_class.rb",
    "lib/scout/log/fingerprint.rb",
    "lib/scout/log/progress.rb",
    "lib/scout/log/progress/report.rb",
    "lib/scout/log/progress/util.rb",
    "lib/scout/meta_extension.rb",
    "lib/scout/path.rb",
    "lib/scout/path/find.rb",
    "lib/scout/tmpfile.rb",
    "scout-gear.gemspec",
    "test/scout/indiferent_hash/test_options.rb",
    "test/scout/log/test_progress.rb",
    "test/scout/path/test_find.rb",
    "test/scout/test_indiferent_hash.rb",
    "test/scout/test_log.rb",
    "test/scout/test_meta_extension.rb",
    "test/scout/test_path.rb",
    "test/scout/test_tmpfile.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/mikisvaz/scout-gear".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.4.6".freeze
  s.summary = "basic gear for scouts".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<term-ansicolor>.freeze, [">= 0"])
  s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
  s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
  s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
  s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
end

