#!/usr/bin/env ruby

require 'scout'
require 'scout/knowledge_base'

$0 = "scout #{$previous_commands.any? ? $previous_commands*" " + " " : "" }#{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Register a database

$ #{$0} [<options>] <name> <filename>

-h--help Print this help
-kb--knowledge_base* Knowlege base name (or :default)
-s--source* Source description
-t--target* Target description
-f--fields* Fields to consider
-n--namespace* Namespace
-i--identifiers* Identifiers
-u--undirected
-d--description* Database description
EOF
if options.delete :help
  if defined? scout_usage
    scout_usage
  else
    puts SOPT.doc
  end
  exit 0
end

name, file = ARGV


raise MissingParameterException, :name if name.nil?
raise MissingParameterException, :file if file.nil?

knowledge_base = IndiferentHash.process_options options, :knowledge_base
knowledge_base = KnowledgeBase.load knowledge_base || :default

options[:fields] = options[:fields].split(/,\s*/) if options[:fields]
file = Scout.identify(File.expand_path(file))
knowledge_base.register name, Scout.identify(file), options

knowledge_base.save
