#!/usr/bin/env ruby
case
when File.exist?(file = File.join(__dir__, '../modules/rbbt-util/bin/rbbt'))
  $LOAD_PATH.unshift(lib_dir = File.join(file, '../..', 'lib'))
  require_relative File.join(lib_dir,'rbbt-util')
  Path.add_path(:rbbt, File.expand_path(File.join(File.dirname(lib_dir), "/{TOPLEVEL}/{SUBPATH}")))
  Path.default_pkgdir = Rbbt
  load file
when File.exist?(file = File.join(ENV["HOME"], 'git/scout-gear/modules/rbbt-util/bin/rbbt'))
  $LOAD_PATH.unshift(lib_dir = File.join(file, '../..', 'lib'))
  require_relative File.join(lib_dir,'rbbt-util')
  Path.add_path(:rbbt, File.expand_path(File.join(File.dirname(lib_dir), "/{TOPLEVEL}/{SUBPATH}")))
  Path.default_pkgdir = Rbbt
  load file
when File.exist?(file = File.join(ENV["HOME"], 'git/rbbt-util/bin/rbbt'))
  $LOAD_PATH.unshift(lib_dir = File.join(file, '../..', 'lib'))
  require_relative File.join(lib_dir,'rbbt-util')
  Path.add_path(:rbbt, File.expand_path(File.join(File.dirname(lib_dir), "/{TOPLEVEL}/{SUBPATH}")))
  Path.default_pkgdir = Rbbt
  load file
else
  raise "Cant find rbbt"
end
