#!/usr/bin/env ruby

require 'scout'

$0 = "scout #{$previous_commands.any? ? $previous_commands*" " + " " : "" }#{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Show info from job

$ #{$0} [<options>] <step_path>

-h--help Print this help
EOF
if options[:help]
  if defined? scout_usage
    scout_usage 
  else
    puts SOPT.doc
  end
  exit 0
end

path = ARGV.first
raise MissingParameterException.new :step_path if path.nil?
step = Step.load(path.dup)

puts step.info.to_json

