#!/usr/bin/env ruby

require 'scout'
require 'scout/association'

$0 = "scout #{$previous_commands.any? ? $previous_commands*" " + " " : "" }#{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Show a database

$ #{$0} [<options>] <name>

-h--help Print this help
EOF
if options[:help]
  if defined? scout_usage
    scout_usage 
  else
    puts SOPT.doc
  end
  exit 0
end


registry = begin
             Scout.var.databases.registry.yaml
           rescue
             {}
           end

name = ARGV.first

if name.nil?
  puts registry.keys * "\n"

else

  raise ParameterException "Database #{name} not found Options: #{Log.fingerprint registry.keys}" unless registry.include? name

  file, options = registry[name]

  IndiferentHash.setup(options)
  options.keys_to_sym!

  Log.tsv Association.database(file, **options)
end
